version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=bitnami_myapp
  open-ticket-backend:
    image: docker.io/bitnami/laravel:9
    container_name: open-ticket-backend
    ports:
      - '8002:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    command: "composer install"
    volumes:
      - './backend:/app'
    depends_on:
      - mariadb
  open-ticket-frontend:
    image: docker.io/bitnami/node:18
    command: "sh -c 'npm install && npm start'"
    ports:
      - '3000:3000'
    container_name: open-ticket-frontend
    volumes:
      - './frontend:/app'