version: '3.9'

services:
  image:
    container_name: openticket
    image: openticket
    build:
      context: .

  bin: &base
    container_name: bin.openticket
    profiles:
      - bin
    image: openticket
    depends_on:
      - image
    entrypoint:
      - php
      - bin/hyperf.php
    env_file:
      - .env
    volumes:
      - ./:/opt/www

  composer:
    <<: *base
    container_name: composer.openticket
    profiles:
      - composer
    entrypoint:
      - composer
    command: validate

  app:
    <<: *base
    container_name: app.openticket
    profiles: []
    entrypoint:
      - php
      - bin/hyperf.php
      - server:watch
    ports:
      - "9501:9501"

  db:
    container_name: db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: openticket
      MYSQL_DATABASE: openticket
    ports:
      - "3306:3306"
    volumes:
      - mysql.openticket.dev:/var/lib/mysql

  cache:
    container_name: cache
    image: 'redis:6.2.6'

  
  amqp:
    image: rabbitmq:3-management-alpine
    container_name: amqp
    ports: 
    - 25672:25672 # (erlang) communication between the nodes and CLI tool
    - 15672:15672 # communication with the web management API 
    volumes:
    - /docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    - /docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: always

volumes:
  mysql.openticket.dev:
    driver: local
  
